-- Schema initialization for H2 database
-- This file contains all table creation statements

-- 创建 chat_messages 表，用于存储会话消息 JSON 数据（H2兼容版本）
CREATE TABLE IF NOT EXISTS CHAT_MESSAGES (
    id INT IDENTITY PRIMARY KEY,
    MESSAGE_ID VARCHAR(64) NOT NULL,
    CONTENT TEXT NOT NULL,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 添加索引以提高查询性能
CREATE INDEX IF NOT EXISTS IDX_MESSAGE_ID ON CHAT_MESSAGES(MESSAGE_ID);
CREATE INDEX IF NOT EXISTS IDX_CREATE_TIME ON CHAT_MESSAGES(CREATE_TIME);
